apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: opendata-ingestion
  namespace: default
spec:
  createingress: true
  functionref:
    functionweights: null
    name: opendata-ingestion
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: "*"
    path: /test
    tls: ""
  method: GET
  relativeurl: /test
